### ISSUE TITLE
Store Animals locally

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#13]
It's connecting to the #4 issue.

We should give a chance to Room: https://medium.com/@ajaysaini.official/building-database-with-room-persistence-library-ecf7d0b8f3e9

**Comment by ezisazis** [comment]
OFC fist we should come up with a MVP DB structure.

**Comment by sionleroux** [comment]
> DB structure

The animals are stored in memory as a [linked list](https://en.wikipedia.org/wiki/Linked_list), why can't we just serialise that to the filesystem? It would map awkwardly to a relational database.

**Comment by ezisazis** [comment]
That's cool too, but we still need to organise the data somehow

**Comment by sionleroux** [comment]
OK, what I said before was wrong, at some point it turned out a linked list wouldn't be enough because guesses can go in either Yes or No direction for an arbitrary number of steps (as opposed to just one direction like in a linked list) so this is actually a [binary tree](https://en.wikipedia.org/wiki/Binary_tree).

> we still need to organise the data somehow

It is currently organised as a tree structure, with the root node [spontaneously declared in Greeting.java](https://github.com/sinisterstuf/GuessTheAnimal/blob/82ee376e1b780b53ede60cb70ebbc1aed3590901/app/src/main/java/org/sinisterstuf/guesstheanimal/Greeting.java#L27-L29) (this could be improved) and other animals added onto its leaf nodes. When learning new animals we replace the old root with the new root we created at the end of the learning process (there are several LearnX.java files for that) because it's currently immutable (I'm undecided as to whether that is good or bad in this situation).

The main thing that's needed is to serialise this to a file when the app closes and deserialise it when the app starts up, so I've already made the relevant classes _serialisable_, all that's left is to get access to the filesystem, e.g. sdcard and add instructions to do the actual read/write work.

**Comment by ezisazis** [comment]
Yeah but right now an animal only has 1 question with a true or false answer? There should be lots of different questions which can re-used for other animals too and we could store the answers for them, right?

**Comment by sionleroux** [comment]
> different questions which can re-used for other animals

Nope, it's stored as as a tree so that there is one path to each animal. In the tree each node is a question and each branch is Yes or No, and each branch leads to another node which if it is a leaf node, is an animal, and if it is a non-leaf node, is another question, which leads to another node and so on. When the player reaches a leaf node which is _not_ the correct animal, we add a new non-leaf node there (a question) with Yes/No branches pointing to the animal that was guessed incorrectly on one side and the animal we just learnt on the other. That way the questions should lead filter reach the correct animal in a fairly efficient way, without repeating questions. I can draw a diagram of this if it helps because I'm not sure I was able to phrase it clearly here.

Something that is still missing is balancing the tree. Closely related to this is #1 which might solve the problem.
